### ISSUE TITLE
Nullpointer Exception when trying to show error

### ISSUE THREAD

**Issue by fizzl** [fizzl/OneCallCaspian#10]
Error Report collected on : Tue Mar 03 17:25:07 IRST 2015

Informations :
==============

Version : null
Build Number : null (8)
Package : uk.co.onecallcaspian
FilePath : /data/data/uk.co.onecallcaspian/files
Phone ModelHTC Desire C
Android Version : 4.0.3
Board : golfu
Brand : htc_asia_wwe
Device : golfu
Display : IML74K
Finger Print : htc_asia_wwe/htc_golfu/golfu:4.0.3/IML74K/132666.3:user/release-keys
Host : abm032
ID : IML74K
Model : HTC Desire C
Product : htc_golfu
Tags : release-keys
Time : 1386177382000
Type : user
User : unknown
Total Internal memory : 1007308800
Available Internal memory : 102014976
Custom Informations :
=====================

Stack : 
======= 
java.lang.NullPointerException
at android.widget.Toast.<init>(Toast.java:92)
at android.widget.Toast.makeText(Toast.java:233)
at uk.co.onecallcaspian.ChatFragment$13.fail(ChatFragment.java:913)
at uk.co.onecallcaspian.custom.filesharing.FilesharingUploadTask.onPostExecute(FilesharingUploadTask.java:119)
at uk.co.onecallcaspian.custom.filesharing.FilesharingUploadTask.onPostExecute(FilesharingUploadTask.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:602)
at android.os.AsyncTask.access$600(AsyncTask.java:156)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:4987)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)

Cause : 
======= 
**** End of current Report ***

**Comment by fizzl** [comment]
Potentially fixed. Waiting for results.

**Comment by fizzl** [comment]
I guess it was fixed.
