### ISSUE TITLE
SoundPlayer crashes on progress change

### ISSUE THREAD

**Issue by fizzl** [fizzl/OneCallCaspian#9]
Error report:

Error Report collected on : Wed Mar 04 04:22:34 IRST 2015

Informations :
==============

Version : null
Build Number : null (9)
Package : uk.co.onecallcaspian
FilePath : /data/data/uk.co.onecallcaspian/files
Phone ModelHTC Desire C
Android Version : 4.0.3
Board : golfu
Brand : htc_asia_wwe
Device : golfu
Display : IML74K
Finger Print : htc_asia_wwe/htc_golfu/golfu:4.0.3/IML74K/132666.3:user/release-keys
Host : abm032
ID : IML74K
Model : HTC Desire C
Product : htc_golfu
Tags : release-keys
Time : 1386177382000
Type : user
User : unknown
Total Internal memory : 1007308800
Available Internal memory : 110600192
Custom Informations :
=====================

Stack : 
======= 
java.lang.NullPointerException
at uk.co.onecallcaspian.custom.filesharing.SoundPlayer$6.onProgressChanged(SoundPlayer.java:217)
at android.widget.SeekBar.onProgressRefresh(SeekBar.java:89)
at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:612)
at android.widget.ProgressBar.refreshProgress(ProgressBar.java:624)
at android.widget.ProgressBar.setProgress(ProgressBar.java:673)
at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:458)
at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:394)
at android.view.View.dispatchTouchEvent(View.java:5568)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6217)
at android.widget.ListView.dispatchTouchEvent(ListView.java:4809)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2070)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1746)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1961)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1398)
at android.app.Activity.dispatchTouchEvent(Activity.java:2428)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1909)
at android.view.View.dispatchPointerEvent(View.java:5748)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3165)
at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2719)
at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:951)
at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2733)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:4987)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)

**Comment by fizzl** [comment]
Potentially fixed. Waiting for results.
